### ISSUE TITLE
[bug] subdir fix due confused rendering

### ISSUE THREAD

**Issue by mckaygerhard** [arnaudsm/raito#15]
from #9 now that mdwiki are defunct i will test this..  the relative link support from @arnaudsm  allow to be the file readable from any git implementation.. 

You are using ROOT for rendering all the things and that's the problem.. and @uli-heller  fixed that! your "relative" inplementation is **from root* and not from the current place!

case1: using "`[Level 2](subdir-01/subdir-02/)`" this is the current supported @arnaudsm **BUT you miscunderstand, it suppost ONLY IF I AM IN UPPER LEVEL ABOVE OF `subdir-01` in current place but due you are using a ROOT global path it's working**

case2: using "`[Level 2](subfolder-02/)`"  this is the correct way if were inside https://github.com/arnaudsm/raito/blob/absolute-link-example/subfolder-01/README.md as you can check github renders incorrectly the link and just show: "https://github.com/arnaudsm/raito/blob/absolute-link-example/subfolder-01/subfolder-01/subfolder-02" noted the duplication of "../subfolder-01/subfolder-01/subfol..." at the github..

so that why @uli-heller  has right here! -> https://stackoverflow.com/questions/24028561/relative-path-in-html

so i suggest that the changes of the @uli-heller  must be implemented, please reopen this issue .. your subdir implementantion are wrong

**Comment by arnaudsm** [comment]
Good find @mckaygerhard, fix in progress in #25 

I'm adding test coverage to make sure it never happens again
