### ISSUE TITLE
[bug] sitePath infinite redirection if runs from userdir module

### ISSUE THREAD

**Issue by mckaygerhard** [arnaudsm/raito#37]
NOTE: this bug are more ancient rather than the last changes you made

## context:

- Apache Userdir: https://httpd.apache.org/docs/2.4/mod/mod_userdir.html
- Nginx userdir:  `alias /home/$1/public_html/$2;` https://www.linode.com/community/questions/6502/nginx-php-in-a-users-public_html
- Lighttpd userdir: https://redmine.lighttpd.net/projects/lighttpd/wiki/Mod_userdir

## Description

i setup to run raito into the user directory, so:

* the user is `general`, 
* the path in webroot is `/home/general/public_html/raito`
* the request looks as `http://localhost/~general/raito/`
* the `sitePath` its set to `/~general/raito/` (also tested `/~general/raito` )
* the browserRouter was test with FALSE (seems related to  comment on https://github.com/arnaudsm/raito/issues/36#issue-1805853979 )

## But resulting

infinite redirections and a url as: `http://localhost/~general/raito/#//~general/raito/#//~general/raito/#//~general/raito/#//~general/raito/#//~general/raito/#//~general/raito/#/`

but if we change the `browserRouter` to true it work! of course cos only index.html its valid rendering

**Comment by arnaudsm** [comment]
Can you test on the last version ? I rewrote a significant portion last night

**Comment by mckaygerhard** [comment]
closed cos with https://github.com/arnaudsm/raito/commit/0a1d9e9c62d45417732429f564ba719593e19db8#r121693269  worked!

but now this  commit forced that **`sitePath` require always a `/` at the beginning and end of the configured path**, that is not bad but is not so user friendly due missing documentation, i can help to improve the documentation (that is so so so simplistic)
