### ISSUE TITLE
Chart.js integration

### ISSUE THREAD

**Issue by MBlaschek** [arnaudsm/raito#6]
Hi,
I would like to include a chart in the markdown website.
for example from [chart.js](https://www.chartjs.org/docs/latest/getting-started/)
```html
# My Chart
<canvas id="myChart"></canvas>
<script>
const labels = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
];
const data = {
  labels: labels,
  datasets: [{
    label: 'My First dataset',
    backgroundColor: 'rgb(255, 99, 132)',
    borderColor: 'rgb(255, 99, 132)',
    data: [0, 10, 5, 2, 20, 30, 45],
  }]
};
const config = {
  type: 'line',
  data: data,
  options: {}
};
  const myChart = new Chart(
    document.getElementById('myChart'),
    config
  );
</script>
```
I put this in a markdown file and added a link to it, like the examples.md

Not sure if that makes sense to you. But I would really appreciate your help.
Thanks
Great project!

**Comment by arnaudsm** [comment]
That's a great idea!
You'd need to import `chart.js` then run your Javascript once the markdown has loaded.

I created a special branch for you with an example : https://github.com/arnaudsm/raito/tree/chartjs-example

Please close the issue if you're satisfied with the solution :smiley:

**Comment by arnaudsm** [comment]
Closing the issue for inactivity. Reopen it if you have more questions about the branch
